### ISSUE TITLE
Remain faithful to RFC 2812 IRC standards

### ISSUE THREAD

**Issue by Decagon** [atillabyte/TVChatLog#1]
To remain compliant with the IRC standards, the maximum message length should not exceed 512 characters, including the line break.

> IRC messages are always lines of characters terminated with a CR-LF
>    (Carriage Return - Line Feed) pair, and these messages SHALL NOT
>    exceed 512 characters in length, counting all characters including
>    the trailing CR-LF. Thus, there are 510 characters maximum allowed
>    for the command and its parameters.  There is no provision for
>    continuation of message lines.  See section 6 for more details about
>    current implementations. (Kalt, 2000)

The messages should be split if they exceed the maximum length.

Kalt, C. “Internet Relay Chat: Client Protocol.” IETF Tools, 2000, tools.ietf.org/html/rfc2812.

**Comment by atillabyte** [comment]
I do realize that there isn't a strict compliance with the IRC standards.

I think perhaps the project intentions were too vague from the onset but, as it currently stands, there isn't any support for interfacing between TeamViewer chats and an IRC server; only exporting logs to a text file.

The description mentioned IRC as a means for describing the formatting style of the export.
`'[%s] %s: %s' % (time, username, message)` rather than strictly according to the IRC specs.

Thanks for the feedback. I'll go ahead and clarify that in the description. :)
